# Use the official Node.js 19 image as base
FROM node:19

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port that the Vite server runs on
EXPOSE 2400

# Start the Vite development server
CMD ["npm", "run", "dev"]
