# docker-compose.yml
version: '3.8'
services:
  recipes-server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on:
      - prisma
  prisma:
    image: prismagraphql/prisma:1.34
    ports:
      - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql-db
            port: 3306
            user: root
            password: prisma
    volumes:
      - ./server/prisma:/prisma
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes: 
      - mysql:/var/lib/mysql
  # prisma:
  #   image: prismagraphql/prisma:1.34
  #   ports:
  #     - 4466:4466
  #   environment:
  #     PRISMA_CONFIG: |
  #       port: 4466
  #       databases:
  #         default:
  #           connector: sqlite
  #           host: 127.0.0.1
  #           user: root
  #   volumes:
  #     - ./server/prisma:/prisma
  recipes-client:
    build:
      context: client
      dockerfile: Dockerfile.vite
    ports:
      - 2400:2400
    depends_on:
      - recipes-server
  prometheus:
    image: prom/prometheus
    volumes:
      - ./server/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
volumes:
  prometheus-storage:
  grafana-storage:
  mysql: 