# docker-compose.yml
version: '3.8'
services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on:
      - prisma
  prisma:
    image: prismagraphql/prisma:1.34
    ports:
      - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: sqlite
            databaseFile: /prisma/dev.db
    volumes:
      - ./prisma:/prisma
  vite-react:
    build:
      context: .
      dockerfile: Dockerfile.vite
    ports:
      - 3000:3000
    depends_on:
      - express
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000x  
volumes:
  prometheus-storage:
  grafana-storage: