openapi: 3.0.3
info:
  title: Ingredient
  description: Restaurent Ingredient Mangment API
  version: 0.0.1
tags:
  - name: ingredient managment
  
  
  
paths:
  /ingredients/{id}:
    parameters:
      - name: id
        in: path
        description: ingredient ID
        required: true
        schema:
          type: integer
          format: int64
####################
    get:
      tags:
        - ingredient managment
      summary: Get an existing ingredient
      description: Get an existing ingredient by Id
      operationId: getIngredient        
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        '404':
          description: Ingredient not found
####################
    put:
      tags:
        - ingredient managment
      summary: Update an existing ingredient
      description: Update an existing ingredient by Id
      operationId: updateIngredient
      requestBody:
        description: Update an existent ingredient
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ingredient'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        '400':
          description: Invalid ID supplied
        '404':
          description: Ingredient not found
####################
    delete:
      summary: Remove a ingredient
      description: Remove a ingredient by Id
      operationId: deleteIngredient
      responses:
        '200':
          description: Successful operation
        '404':
          description: ingredient not found
      tags:
        - ingredient managment 
        
        
        
####################
  /ingredients:
    post:
      summary: Create a ingredient
      description: Create a ingredient
      operationId: createIngredient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ingredient'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid data supplied
      tags:
        - ingredient managment
####################
    get:
      tags:
        - ingredient managment
      summary: Get all existing ingredients
      description: Get all existing ingredients (paginated)
      operationId: getIngredients
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'
                  
                  
                  
           
##############################################
    

    









###############################################################################

components:
  schemas:
    Ingredient:
      required:
        - name
        - ingredients
        
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
          
        name:
          type: string
          example: poire
        category : 
          type : string 
          example: "feculent"
        
        season: 
          type : string 
          example : "hiver"
          enum: ["hiver", "printemps", "ete", "autone"]
  requestBodies:
    Recipe:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Ingredient'
